import Link from "next/link";
import { createWorkOrder } from "@/app/dashboard/work-orders/actions";
import { PageHeader } from "@/components/PageHeader";
import { createWorkOrderService } from "@/services/workOrderFactory";

export const dynamic = "force-dynamic";
export default async function NewWorkOrderPage({ searchParams }: { searchParams: Promise<{ assetId?: string }> }) {
  const [assets, params] = await Promise.all([createWorkOrderService().listAssetOptions(), searchParams]);
  return <div className="space-y-6"><Link href="/dashboard/work-orders" className="text-sm font-medium text-cyan-600">← Work orders</Link><PageHeader title="Create work order" description="Create a validated engineering task and associate it with an asset."/><form action={createWorkOrder} className="grid gap-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:grid-cols-2 dark:border-slate-800 dark:bg-slate-900"><label className="text-sm font-medium">Asset<select name="assetId" required defaultValue={params.assetId ?? ""} className="mt-2 w-full rounded-xl border border-slate-300 bg-transparent px-3 py-2 dark:border-slate-700"><option value="" disabled>Select asset</option>{assets.map((asset) => <option key={asset.assetId} value={asset.assetId}>{asset.assetId} · {asset.name}</option>)}</select></label><label className="text-sm font-medium">Priority<select name="priority" defaultValue="Medium" className="mt-2 w-full rounded-xl border border-slate-300 bg-transparent px-3 py-2 dark:border-slate-700">{["Low","Medium","High","Critical"].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-sm font-medium md:col-span-2">Title<input name="title" required minLength={3} maxLength={160} className="mt-2 w-full rounded-xl border border-slate-300 bg-transparent px-3 py-2 dark:border-slate-700"/></label><label className="text-sm font-medium md:col-span-2">Description<textarea name="description" required minLength={3} rows={5} className="mt-2 w-full rounded-xl border border-slate-300 bg-transparent px-3 py-2 dark:border-slate-700"/></label><label className="text-sm font-medium">Assign to<input name="assignedTo" placeholder="Engineer or team" className="mt-2 w-full rounded-xl border border-slate-300 bg-transparent px-3 py-2 dark:border-slate-700"/></label><div/><label className="text-sm font-medium">Scheduled start<input type="datetime-local" name="scheduledStart" className="mt-2 w-full rounded-xl border border-slate-300 bg-transparent px-3 py-2 dark:border-slate-700"/></label><label className="text-sm font-medium">Due date<input type="datetime-local" name="dueDate" className="mt-2 w-full rounded-xl border border-slate-300 bg-transparent px-3 py-2 dark:border-slate-700"/></label><div className="md:col-span-2"><button className="rounded-full bg-cyan-500 px-5 py-3 text-sm font-medium text-white">Create work order</button></div></form></div>;
}
