import { Card } from "@/components/Card";
import { PageHeader } from "@/components/PageHeader";
import { createWorkOrderService } from "@/services/workOrderFactory";
import { createEngineerService } from "@/services/engineerFactory";
import { addEngineerAvailability, addEngineerCertification, addEngineerSkill, createEngineer } from "./actions";

export const dynamic = "force-dynamic";
const field = "rounded-xl border border-slate-300 bg-transparent px-3 py-2 text-sm dark:border-slate-700";
export default async function EngineersPage({ searchParams }: { searchParams: Promise<{ workOrderId?: string }> }) {
  const service = createEngineerService(); const params = await searchParams;
  const [engineers, workOrders] = await Promise.all([service.listEngineers(), createWorkOrderService().list({})]);
  const recommendations = params.workOrderId ? await service.recommend({ workOrderId: params.workOrderId }) : [];
  const available = engineers.filter((engineer) => engineer.activeWorkOrders < engineer.maxConcurrentWorkOrders && !engineer.availability.some((slot) => slot.startsAt <= new Date() && slot.endsAt >= new Date() && slot.status !== "Available")).length;
  return <div className="space-y-6"><PageHeader title="Engineers" description="Manage qualifications, certification, availability, workload, and evidence-based assignment recommendations."/>
    <div className="grid gap-4 sm:grid-cols-3"><Card title="Engineers"><p className="text-3xl font-semibold">{engineers.length}</p></Card><Card title="Available now"><p className="text-3xl font-semibold">{available}</p></Card><Card title="Active assignments"><p className="text-3xl font-semibold">{engineers.reduce((sum, item) => sum + item.activeWorkOrders, 0)}</p></Card></div>
    <Card title="Assignment recommendations" description="Ranks active engineers by matching skills, availability, and current workload."><form className="flex gap-3"><select name="workOrderId" defaultValue={params.workOrderId ?? ""} className={`${field} min-w-0 flex-1`}><option value="">Select a work order</option>{workOrders.filter((order) => !["Completed", "Cancelled"].includes(order.status)).map((order) => <option key={order.id} value={order.id}>{order.priority} · {order.title}</option>)}</select><button className="rounded-xl bg-cyan-600 px-4 py-2 text-sm font-semibold text-white">Recommend</button></form>{recommendations.length ? <div className="mt-4 divide-y divide-slate-200 dark:divide-slate-800">{recommendations.map((item) => <div key={item.engineerId} className="grid gap-2 py-3 sm:grid-cols-[1fr_auto]"><div><p className="font-semibold">{item.engineerName}</p><p className="text-xs text-slate-500">{item.reasons.join(" ")}</p></div><span className={`self-center text-sm font-semibold ${item.available ? "text-emerald-600" : "text-amber-600"}`}>{item.score}% match</span></div>)}</div> : null}</Card>
    <Card title="Add engineer"><form action={createEngineer} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><input name="employeeNumber" required placeholder="Employee number" className={field}/><input name="name" required placeholder="Full name" className={field}/><input name="email" type="email" required placeholder="Email" className={field}/><input name="maxConcurrentWorkOrders" type="number" min="1" max="50" defaultValue="5" className={field}/><button className="rounded-xl bg-cyan-600 px-4 py-2 text-sm font-semibold text-white">Add engineer</button></form></Card>
    <div className="grid gap-4 xl:grid-cols-2">{engineers.map((engineer) => <Card key={engineer.id} title={engineer.name} description={`${engineer.employeeNumber} · ${engineer.email}`}><div className="space-y-4 text-sm"><p>{engineer.activeWorkOrders}/{engineer.maxConcurrentWorkOrders} active work orders · {engineer.teams.map((team) => team.name).join(", ") || "No team"}</p><div><p className="font-medium">Skills</p><p className="text-slate-500">{engineer.skills.map((skill) => `${skill.name} (${skill.proficiency}/5)`).join(", ") || "None recorded"}</p></div><div><p className="font-medium">Certifications</p><p className="text-slate-500">{engineer.certifications.map((certificate) => `${certificate.name}${certificate.expiresAt ? ` · expires ${certificate.expiresAt.toLocaleDateString()}` : ""}`).join(", ") || "None recorded"}</p></div><details><summary className="cursor-pointer font-medium text-cyan-700">Manage profile</summary><div className="mt-3 space-y-3"><form action={addEngineerSkill} className="grid grid-cols-2 gap-2"><input type="hidden" name="engineerId" value={engineer.id}/><input name="name" required placeholder="Skill" className={field}/><input name="category" required placeholder="Category" className={field}/><input name="proficiency" type="number" min="1" max="5" required placeholder="Level 1-5" className={field}/><input name="yearsExperience" type="number" min="0" step="0.5" required placeholder="Years" className={field}/><button className="col-span-2 rounded-xl border border-cyan-600 px-3 py-2 font-medium text-cyan-700">Save skill</button></form><form action={addEngineerCertification} className="grid grid-cols-2 gap-2"><input type="hidden" name="engineerId" value={engineer.id}/><input name="name" required placeholder="Certification" className={field}/><input name="issuer" required placeholder="Issuer" className={field}/><input name="credentialCode" placeholder="Credential code" className={field}/><input name="expiresAt" type="date" className={field}/><button className="col-span-2 rounded-xl border border-cyan-600 px-3 py-2 font-medium text-cyan-700">Add certification</button></form><form action={addEngineerAvailability} className="grid grid-cols-2 gap-2"><input type="hidden" name="engineerId" value={engineer.id}/><input name="startsAt" type="datetime-local" required className={field}/><input name="endsAt" type="datetime-local" required className={field}/><select name="status" className={field}><option>Available</option><option>Unavailable</option><option>Leave</option><option>Training</option></select><input name="note" placeholder="Note" className={field}/><button className="col-span-2 rounded-xl border border-cyan-600 px-3 py-2 font-medium text-cyan-700">Add availability</button></form></div></details></div></Card>)}</div>
  </div>;
}
