import type { AlertFinding, AlertMetric, AlertSeverity } from "@/domain/entities/Alert";
import type { RecommendationDto } from "@/dto/recommendation.dto";

type Rule = Pick<RecommendationDto, "rootCause" | "actions" | "requiredTools" | "requiredSkills" | "estimatedDowntime" | "safetyWarnings" | "followUpInspection">;
const rules: Record<AlertMetric, Rule> = {
  temperature: { rootCause: "Probable excessive thermal load, impaired cooling, or insufficient lubrication.", actions: ["Reduce load and inspect cooling paths, lubrication, and bearing temperature.", "Check the trend against rated operating temperature before returning to normal load."], requiredTools: ["Infrared thermometer", "Thermal camera", "Lubrication kit"], requiredSkills: ["Mechanical maintenance", "Thermal inspection"], estimatedDowntime: "30–90 minutes", safetyWarnings: ["Do not touch hot surfaces without confirming a safe temperature.", "Isolate the asset if temperature continues to rise."], followUpInspection: "Repeat temperature and lubrication inspection within 4 operating hours." },
  vibration: { rootCause: "Probable bearing wear, shaft misalignment, looseness, or rotating imbalance.", actions: ["Inspect bearings, mounts, coupling alignment, and rotating balance.", "Capture a vibration spectrum before replacing components."], requiredTools: ["Vibration analyser", "Laser alignment tool", "Torque wrench"], requiredSkills: ["Vibration analysis", "Rotating equipment maintenance"], estimatedDowntime: "1–3 hours", safetyWarnings: ["Keep clear of rotating components and apply lockout/tagout before physical inspection."], followUpInspection: "Repeat vibration measurement after corrective work and again after 8 operating hours." },
  voltage: { rootCause: "Probable supply instability, poor connection, protection-device issue, or incorrect operating voltage.", actions: ["Verify phase voltage, connections, protection devices, and equipment rating.", "Inspect for voltage drop or imbalance under load."], requiredTools: ["CAT-rated multimeter", "Power quality analyser", "Insulated hand tools"], requiredSkills: ["Qualified electrical maintenance", "Power quality analysis"], estimatedDowntime: "45–120 minutes", safetyWarnings: ["Electrical testing must be completed by an authorised person using the required PPE.", "De-energise and prove dead before tightening connections."], followUpInspection: "Log voltage under normal load after repair and review again within 24 hours." },
  current: { rootCause: "Probable electrical overload, phase imbalance, motor fault, or excessive mechanical resistance.", actions: ["Measure phase current and compare it with nameplate limits.", "Inspect the driven load, motor condition, and electrical connections."], requiredTools: ["Clamp meter", "Insulation resistance tester", "Power quality analyser"], requiredSkills: ["Qualified electrical maintenance", "Motor diagnostics"], estimatedDowntime: "1–2 hours", safetyWarnings: ["Use arc-flash controls and electrically rated PPE.", "Do not reset protection repeatedly without identifying the overload source."], followUpInspection: "Recheck phase current after corrective work and at the next loaded operating cycle." },
  humidity: { rootCause: "Probable enclosure leakage, condensation, inadequate ventilation, or moisture ingress.", actions: ["Inspect enclosure seals, drains, ventilation, and condensation controls.", "Dry and test affected electrical components before energisation."], requiredTools: ["Hygrometer", "Moisture meter", "Insulation resistance tester"], requiredSkills: ["Environmental inspection", "Electrical maintenance"], estimatedDowntime: "30–120 minutes", safetyWarnings: ["Isolate electrical equipment if moisture is present inside the enclosure."], followUpInspection: "Repeat humidity and enclosure inspection after 24 hours and after the next weather cycle." },
  overall_health: { rootCause: "Multiple condition indicators are reducing the calculated asset health score.", actions: ["Review health drivers, recent telemetry, inspection findings, and maintenance history.", "Perform a condition-based engineering inspection focused on the lowest scoring systems."], requiredTools: ["Inspection checklist", "Asset history", "Relevant diagnostic instruments"], requiredSkills: ["Condition monitoring", "Reliability engineering"], estimatedDowntime: "1–4 hours", safetyWarnings: ["Treat low safety-score drivers as stop-work conditions until assessed."], followUpInspection: "Recalculate health immediately after corrective work and review the trend within 7 days." },
  failure_probability: { rootCause: "Combined health, fault, hazard, and telemetry indicators imply elevated near-term failure risk.", actions: ["Review the contributing risk drivers and restrict operation where appropriate.", "Plan risk-based maintenance and verify critical failure modes before continued service."], requiredTools: ["Failure-mode checklist", "Asset history", "Relevant diagnostic instruments"], requiredSkills: ["Reliability engineering", "Failure mode analysis"], estimatedDowntime: "2–8 hours", safetyWarnings: ["Do not continue operation when the predicted failure mode can endanger personnel or containment."], followUpInspection: "Complete a qualified engineering inspection before unrestricted operation and recalculate risk afterward." },
};
const priorities: Record<AlertSeverity, RecommendationDto["priority"]> = { Critical: "Immediate", High: "Urgent", Medium: "Planned", Low: "Monitor" };
const confidence: Record<AlertSeverity, number> = { Critical: 0.9, High: 0.85, Medium: 0.78, Low: 0.7 };
export class EngineeringRuleEngine { evaluate(finding: AlertFinding): RecommendationDto { const rule = rules[finding.metric]; return { ...rule, priority: priorities[finding.severity], confidence: confidence[finding.severity], evidence: [`${finding.title}: observed ${finding.observedValue}; ${finding.severity.toLowerCase()} threshold ${finding.thresholdValue}.`, `Trigger source: ${finding.triggerType ?? finding.source}.`] }; } }
