import { describe, expect, it } from "vitest";
import type { KnowledgeEdge, KnowledgeFact, KnowledgeGraphResult, KnowledgeNode } from "@/domain/entities/EngineeringKnowledge";
import type { KnowledgeBuildDto, KnowledgeSearchDto, KnowledgeTraversalDto } from "@/dto/knowledge.dto";
import type { KnowledgeRepository } from "@/repositories/KnowledgeRepository";
import { KnowledgeGraph } from "@/services/KnowledgeGraph";
import { KnowledgeSearch } from "@/services/KnowledgeSearch";

class InMemoryKnowledgeRepository implements KnowledgeRepository {
  nodes: KnowledgeNode[] = []; edges: KnowledgeEdge[] = []; facts: KnowledgeFact[] = []; private sequence = 0;
  private now = new Date("2026-08-29");
  async apply(input: KnowledgeBuildDto): Promise<KnowledgeGraphResult> {
    for (const value of input.nodes) { const existing = this.nodes.find((node) => node.organisationId === value.organisationId && node.nodeType === value.nodeType && node.externalKey === value.externalKey); if (existing) { const count = existing.occurrenceCount + value.occurrenceCount; existing.confidence = (existing.confidence * existing.occurrenceCount + value.confidence * value.occurrenceCount) / count; existing.occurrenceCount = count; } else this.nodes.push({ id: `n${++this.sequence}`, organisationId: value.organisationId, categoryId: null, nodeType: value.nodeType, externalKey: value.externalKey, label: value.label, description: value.description ?? null, confidence: value.confidence, occurrenceCount: value.occurrenceCount, createdAt: this.now, updatedAt: this.now, facts: [] }); }
    for (const value of input.edges) { const from = this.nodes.find((node) => node.organisationId === value.organisationId && node.nodeType === value.fromNodeType && node.externalKey === value.fromNodeKey)!; const to = this.nodes.find((node) => node.organisationId === value.organisationId && node.nodeType === value.toNodeType && node.externalKey === value.toNodeKey)!; if (!this.edges.some((edge) => edge.organisationId === value.organisationId && edge.fromNodeId === from.id && edge.toNodeId === to.id && edge.relationship === value.relationship)) this.edges.push({ id: `e${++this.sequence}`, organisationId: value.organisationId, fromNodeId: from.id, toNodeId: to.id, relationship: value.relationship, confidence: value.confidence, occurrenceCount: 1, sourceMemoryId: value.sourceMemoryId ?? null, createdAt: this.now, updatedAt: this.now }); }
    for (const value of input.facts) { const node = this.nodes.find((item) => item.organisationId === value.organisationId && item.nodeType === value.nodeType && item.externalKey === value.nodeKey)!; if (!this.facts.some((fact) => fact.organisationId === value.organisationId && fact.nodeId === node.id && fact.predicate === value.predicate && fact.value === value.value)) this.facts.push({ id: `f${++this.sequence}`, organisationId: value.organisationId, nodeId: node.id, predicate: value.predicate, value: value.value, confidence: value.confidence, occurrenceCount: 1, sourceMemoryId: value.sourceMemoryId ?? null, createdAt: this.now, updatedAt: this.now }); }
    return this.result(input.nodes[0].organisationId, this.nodes.filter((node) => node.organisationId === input.nodes[0].organisationId));
  }
  async search(input: KnowledgeSearchDto) { const terms = input.query.toLowerCase().split(/\s+/); const nodes = this.nodes.filter((node) => node.organisationId === input.organisationId && (!input.nodeTypes || input.nodeTypes.includes(node.nodeType)) && (!input.query || terms.some((term) => `${node.label} ${node.description ?? ""}`.toLowerCase().includes(term))) && (!input.assetIds?.length || node.nodeType !== "Asset" || input.assetIds.map((id) => id.toLowerCase()).includes(node.externalKey))).slice(0, input.limit); return this.result(input.organisationId, nodes); }
  async traverse(input: KnowledgeTraversalDto) { const visited = new Set([input.nodeId]); let frontier = [input.nodeId]; for (let depth = 0; depth < input.depth; depth++) { const adjacent = this.edges.filter((edge) => edge.organisationId === input.organisationId && (frontier.includes(edge.fromNodeId) || frontier.includes(edge.toNodeId))); frontier = [...new Set(adjacent.flatMap((edge) => [edge.fromNodeId, edge.toNodeId]).filter((id) => !visited.has(id)))]; frontier.forEach((id) => visited.add(id)); } return this.result(input.organisationId, this.nodes.filter((node) => visited.has(node.id))); }
  private result(organisationId: string, nodes: KnowledgeNode[]) { const ids = new Set(nodes.map((node) => node.id)); return { nodes, edges: this.edges.filter((edge) => edge.organisationId === organisationId && ids.has(edge.fromNodeId) && ids.has(edge.toNodeId)), facts: this.facts.filter((fact) => fact.organisationId === organisationId && ids.has(fact.nodeId)) }; }
}

const build = (organisationId: string, confidence = 0.8): KnowledgeBuildDto => ({ categories: [], nodes: [{ organisationId, nodeType: "Asset", externalKey: "mm-1", label: "Pump MM-1", confidence, occurrenceCount: 1 }, { organisationId, nodeType: "Failure", externalKey: "bearing-failure", label: "Bearing failure", confidence, occurrenceCount: 1 }], edges: [{ organisationId, fromNodeKey: "mm-1", fromNodeType: "Asset", toNodeKey: "bearing-failure", toNodeType: "Failure", relationship: "EXPERIENCED_FAILURE", confidence, occurrenceCount: 1 }], facts: [{ organisationId, nodeKey: "bearing-failure", nodeType: "Failure", predicate: "SUMMARY", value: "Excess vibration", confidence, occurrenceCount: 1 }] });

describe("Knowledge graph behavior", () => {
  it("prevents duplicate nodes, edges, and facts and aggregates confidence", async () => { const repository = new InMemoryKnowledgeRepository(); const graph = new KnowledgeGraph(repository); await graph.apply(build("o1", 0.6)); await graph.apply(build("o1", 1)); expect(repository.nodes).toHaveLength(2); expect(repository.edges).toHaveLength(1); expect(repository.facts).toHaveLength(1); expect(repository.nodes[0]).toMatchObject({ occurrenceCount: 2, confidence: 0.8 }); });
  it("traverses connected engineering relationships", async () => { const repository = new InMemoryKnowledgeRepository(); await new KnowledgeGraph(repository).apply(build("o1")); const result = await new KnowledgeSearch(repository).traverse({ organisationId: "o1", nodeId: repository.nodes[0].id, depth: 1, limit: 20 }); expect(result.nodes.map((node) => node.nodeType)).toEqual(["Asset", "Failure"]); expect(result.edges).toHaveLength(1); expect(result.facts).toHaveLength(1); });
  it("searches graph text and enforces organisation isolation", async () => { const repository = new InMemoryKnowledgeRepository(); const graph = new KnowledgeGraph(repository); await graph.apply(build("o1")); await graph.apply(build("o2")); const result = await new KnowledgeSearch(repository).search({ organisationId: "o1", query: "bearing", limit: 25 }); expect(result.nodes).toHaveLength(1); expect(result.nodes[0]).toMatchObject({ organisationId: "o1", nodeType: "Failure" }); expect(result.nodes.every((node) => node.organisationId === "o1")).toBe(true); });
});
