import Link from "next/link";
import type { Alert } from "@/domain/entities/Alert";
import { acknowledgeAlert, resolveAlert } from "@/app/dashboard/alerts/actions";
import { RecommendationDetails } from "@/components/alerts/RecommendationDetails";

const tone = { Critical: "border-red-300 bg-red-50 text-red-800 dark:border-red-900 dark:bg-red-950/40 dark:text-red-200", High: "border-orange-300 bg-orange-50 text-orange-800 dark:border-orange-900 dark:bg-orange-950/40 dark:text-orange-200", Medium: "border-amber-300 bg-amber-50 text-amber-800 dark:border-amber-900 dark:bg-amber-950/40 dark:text-amber-200", Low: "border-cyan-300 bg-cyan-50 text-cyan-800 dark:border-cyan-900 dark:bg-cyan-950/40 dark:text-cyan-200" } as const;
const statusTone = { Open: "bg-red-100 text-red-700 dark:bg-red-950/50 dark:text-red-200", Acknowledged: "bg-amber-100 text-amber-700 dark:bg-amber-950/50 dark:text-amber-200", Resolved: "bg-emerald-100 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-200" } as const;

export function AlertList({ alerts, queryString, emptyMessage = "No alerts match the selected filters." }: { alerts: Alert[]; queryString: string; emptyMessage?: string }) {
  if (!alerts.length) return <div className="rounded-2xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500 dark:border-slate-700">{emptyMessage}</div>;
  return <div className="space-y-4">{alerts.map((alert) => <article key={alert.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full border px-3 py-1 text-xs font-semibold ${tone[alert.severity]}`}>{alert.severity}</span><span className={`rounded-full px-3 py-1 text-xs font-medium ${statusTone[alert.status]}`}>{alert.status}</span><span className="text-xs text-slate-500">{alert.category} · {alert.source}</span></div><h2 className="mt-3 text-lg font-semibold">{alert.title}</h2><Link href={`/dashboard/assets/${alert.assetId}`} className="mt-1 inline-block text-sm text-cyan-600 hover:text-cyan-500">{alert.assetId} · {alert.assetName}</Link></div><div className="flex gap-3"><Link href={`/dashboard/alerts?${queryString}${queryString ? "&" : ""}alertId=${alert.id}`} className="text-sm font-medium text-cyan-600 hover:text-cyan-500">Timeline</Link><Link href={`/dashboard/alerts/${alert.id}`} className="text-sm font-medium text-cyan-600 hover:text-cyan-500">Details</Link></div></div><p className="mt-4 text-sm leading-6 text-slate-600 dark:text-slate-300">{alert.description}</p><div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm dark:bg-slate-950"><p className="mb-2 font-medium">Engineering recommendation</p><RecommendationDetails value={alert.recommendation} compact /></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-slate-500">Created {alert.createdAt.toLocaleString("en-GB")}</p><div className="flex gap-2">{alert.status === "Open" ? <form action={acknowledgeAlert}><input type="hidden" name="alertId" value={alert.id} /><button className="rounded-full border border-slate-300 px-4 py-2 text-xs font-medium hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-800">Acknowledge</button></form> : null}{alert.status !== "Resolved" ? <form action={resolveAlert}><input type="hidden" name="alertId" value={alert.id} /><button className="rounded-full bg-cyan-500 px-4 py-2 text-xs font-medium text-white hover:bg-cyan-400">Resolve</button></form> : null}</div></div></article>)}</div>;
}
