import { parseRecommendation } from "@/dto/recommendation.dto";

export function RecommendationDetails({ value, compact = false }: { value: string; compact?: boolean }) {
  const recommendation = parseRecommendation(value);
  if (!recommendation) return <p className="text-sm leading-6 text-slate-600 dark:text-slate-300">{value}</p>;
  if (compact) return <div><p className="text-sm font-medium">{recommendation.rootCause}</p><p className="mt-1 text-sm leading-6 text-slate-600 dark:text-slate-300">{recommendation.actions[0]}</p><p className="mt-2 text-xs text-slate-500">{recommendation.priority} · {Math.round(recommendation.confidence * 100)}% confidence · {recommendation.estimatedDowntime}</p></div>;
  const list = (items: string[]) => <ul className="mt-2 list-disc space-y-1 pl-5 text-sm leading-6 text-slate-600 dark:text-slate-300">{items.map((item) => <li key={item}>{item}</li>)}</ul>;
  return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-3"><div><p className="text-xs uppercase tracking-[0.16em] text-slate-500">Priority</p><p className="mt-1 font-semibold">{recommendation.priority}</p></div><div><p className="text-xs uppercase tracking-[0.16em] text-slate-500">Confidence</p><p className="mt-1 font-semibold">{Math.round(recommendation.confidence * 100)}%</p></div><div><p className="text-xs uppercase tracking-[0.16em] text-slate-500">Estimated downtime</p><p className="mt-1 font-semibold">{recommendation.estimatedDowntime}</p></div></div><div><h3 className="text-sm font-semibold">Likely root cause</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{recommendation.rootCause}</p></div><div><h3 className="text-sm font-semibold">Evidence</h3>{list(recommendation.evidence)}</div><div><h3 className="text-sm font-semibold">Actions</h3>{list(recommendation.actions)}</div><div className="grid gap-5 sm:grid-cols-2"><div><h3 className="text-sm font-semibold">Required tools</h3>{list(recommendation.requiredTools)}</div><div><h3 className="text-sm font-semibold">Required skills</h3>{list(recommendation.requiredSkills)}</div></div>{recommendation.safetyWarnings.length ? <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 dark:border-amber-900 dark:bg-amber-950/30"><h3 className="text-sm font-semibold text-amber-800 dark:text-amber-200">Safety warnings</h3>{list(recommendation.safetyWarnings)}</div> : null}<div><h3 className="text-sm font-semibold">Follow-up inspection</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{recommendation.followUpInspection}</p></div></div>;
}
