import "server-only";
import type { InventoryQuery, Page, StockMovement, StockMovementType } from "@/domain/entities/Inventory";
import type { AdjustInventoryDto, StockMovementDto, TransferInventoryDto } from "@/dto/inventory.dto";
import { prisma } from "@/lib/prisma";
import { InsufficientStockError } from "@/infrastructure/repositories/PrismaInventoryRepository";
import type { StockMovementRepository } from "@/repositories/StockMovementRepository";
const map = (item: { id: string; inventoryItemId: string; destinationInventoryItemId: string | null; workOrderId: string | null; movementType: string; quantity: number; balanceAfter: number; performedBy: string; reference: string | null; notes: string | null; createdAt: Date }): StockMovement => ({ ...item, movementType: item.movementType as StockMovementType });
const deltaFor = (type: StockMovementDto["movementType"], quantity: number) => ["RECEIVED", "RETURNED"].includes(type) ? quantity : -quantity;
export class PrismaStockMovementRepository implements StockMovementRepository {
  async record(input: StockMovementDto) { return prisma.$transaction(async (tx) => { const current = await tx.inventoryItem.findUniqueOrThrow({ where: { id: input.inventoryItemId } }); const delta = deltaFor(input.movementType, input.quantity); const quantity = current.quantity + delta; if (quantity < current.reserved || quantity < 0) throw new InsufficientStockError("Movement would reduce stock below its reserved quantity."); const now = new Date(); await tx.inventoryItem.update({ where: { id: current.id }, data: { quantity, available: quantity - current.reserved, lastMovementAt: now } }); return map(await tx.stockMovement.create({ data: { inventoryItemId: current.id, movementType: input.movementType, quantity: delta, balanceAfter: quantity, performedBy: input.performedBy, reference: input.reference ?? null, notes: input.notes ?? null, createdAt: now } })); }); }
  async adjust(input: AdjustInventoryDto) { return prisma.$transaction(async (tx) => { const current = await tx.inventoryItem.findUniqueOrThrow({ where: { id: input.inventoryItemId } }); const quantity = current.quantity + input.adjustment; if (quantity < current.reserved || quantity < 0) throw new InsufficientStockError("Adjustment would reduce stock below its reserved quantity."); const now = new Date(); await tx.inventoryItem.update({ where: { id: current.id }, data: { quantity, available: quantity - current.reserved, lastMovementAt: now } }); return map(await tx.stockMovement.create({ data: { inventoryItemId: current.id, movementType: "ADJUSTED", quantity: input.adjustment, balanceAfter: quantity, performedBy: input.performedBy, reference: input.reference ?? null, notes: input.notes ?? null, createdAt: now } })); }); }
  async transfer(input: TransferInventoryDto) { return prisma.$transaction(async (tx) => { const [source, destination] = await Promise.all([tx.inventoryItem.findUniqueOrThrow({ where: { id: input.sourceInventoryItemId } }), tx.inventoryItem.findUniqueOrThrow({ where: { id: input.destinationInventoryItemId } })]); if (source.sparePartId !== destination.sparePartId) throw new Error("Transfers require matching spare parts."); if (source.available < input.quantity) throw new InsufficientStockError("Insufficient available stock to transfer."); const now = new Date(); const sourceBalance = source.quantity - input.quantity; const destinationBalance = destination.quantity + input.quantity; await tx.inventoryItem.update({ where: { id: source.id }, data: { quantity: sourceBalance, available: source.available - input.quantity, lastMovementAt: now } }); await tx.inventoryItem.update({ where: { id: destination.id }, data: { quantity: destinationBalance, available: destination.available + input.quantity, lastMovementAt: now } }); const common = { movementType: "TRANSFERRED", performedBy: input.performedBy, reference: input.reference ?? null, notes: input.notes ?? null, createdAt: now }; const outgoing = await tx.stockMovement.create({ data: { ...common, inventoryItemId: source.id, destinationInventoryItemId: destination.id, quantity: -input.quantity, balanceAfter: sourceBalance } }); const incoming = await tx.stockMovement.create({ data: { ...common, inventoryItemId: destination.id, destinationInventoryItemId: source.id, quantity: input.quantity, balanceAfter: destinationBalance } }); return [map(outgoing), map(incoming)]; }); }
  async list(query: InventoryQuery): Promise<Page<StockMovement>> { const where = { inventoryItem: { warehouseId: query.warehouseId || undefined, OR: query.search ? [{ sparePart: { partNumber: { contains: query.search } } }, { sparePart: { name: { contains: query.search } } }] : undefined } }; const [items, total] = await Promise.all([prisma.stockMovement.findMany({ where, orderBy: { createdAt: "desc" }, skip: ((query.page ?? 1) - 1) * (query.pageSize ?? 25), take: query.pageSize ?? 25 }), prisma.stockMovement.count({ where })]); return { items: items.map(map), total, page: query.page ?? 1, pageSize: query.pageSize ?? 25, pageCount: Math.ceil(total / (query.pageSize ?? 25)) }; }
  async deductWorkOrderParts(workOrderId: string, completedAt: Date) { return prisma.$transaction(async (tx) => { const parts = await tx.workOrderPart.findMany({ where: { workOrderId, deductedAt: null }, include: { inventoryItem: { include: { sparePart: { select: { partNumber: true } } } }, workOrder: { select: { assetId: true } } } }); const movements: StockMovement[] = []; for (const part of parts) { const item = part.inventoryItem; if (item.reserved < part.quantity || item.quantity < part.quantity) throw new InsufficientStockError(`Insufficient reserved stock for ${item.sparePart.partNumber}.`); const quantity = item.quantity - part.quantity; const reserved = item.reserved - part.quantity; await tx.inventoryItem.update({ where: { id: item.id }, data: { quantity, reserved, available: quantity - reserved, lastMovementAt: completedAt } }); const movement = await tx.stockMovement.create({ data: { inventoryItemId: item.id, assetId: part.workOrder.assetId, workOrderId, movementType: "CONSUMED", quantity: -part.quantity, balanceAfter: quantity, performedBy: "Work Order Automation", reference: workOrderId, notes: "Automatic consumption for completed work order", createdAt: completedAt } }); await tx.workOrderPart.update({ where: { id: part.id }, data: { deductedAt: completedAt } }); movements.push(map(movement)); } return movements; }); }
}
