import "server-only";
import { prisma } from "@/lib/prisma";
import type { Engineer, Team } from "@/domain/entities/Engineer";
import type { AvailabilityInputDto, CertificationInputDto, CreateEngineerDto, CreateTeamDto, SkillInputDto, TeamMembershipInputDto } from "@/dto/engineer.dto";
import type { AssignmentCandidate, EngineerRepository } from "@/repositories/EngineerRepository";

const engineerInclude = { skills: { include: { skill: true }, orderBy: { proficiency: "desc" as const } }, certifications: { orderBy: { expiresAt: "asc" as const } }, availability: { orderBy: { startsAt: "desc" as const }, take: 20 }, teams: { include: { team: true }, orderBy: { role: "asc" as const } }, _count: { select: { workOrders: { where: { status: { notIn: ["Completed", "Cancelled"] } } } } } };
type EngineerRecord = Awaited<ReturnType<typeof prisma.engineer.findFirstOrThrow>> & { skills: Array<{ proficiency: number; yearsExperience: number; skill: { id: string; name: string; category: string } }>; certifications: Array<{ id: string; name: string; issuer: string; credentialCode: string | null; issuedAt: Date | null; expiresAt: Date | null }>; availability: Array<{ id: string; startsAt: Date; endsAt: Date; status: string; note: string | null }>; teams: Array<{ role: string; team: { id: string; name: string } }>; _count: { workOrders: number } };
const mapEngineer = (item: EngineerRecord): Engineer => ({ id: item.id, employeeNumber: item.employeeNumber, name: item.name, email: item.email, active: item.active, maxConcurrentWorkOrders: item.maxConcurrentWorkOrders, activeWorkOrders: item._count.workOrders, skills: item.skills.map((entry) => ({ id: entry.skill.id, name: entry.skill.name, category: entry.skill.category, proficiency: entry.proficiency, yearsExperience: entry.yearsExperience })), certifications: item.certifications, availability: item.availability.map((entry) => ({ ...entry, status: entry.status as Engineer["availability"][number]["status"] })), teams: item.teams.map((entry) => ({ id: entry.team.id, name: entry.team.name, role: entry.role })) });

export class PrismaEngineerRepository implements EngineerRepository {
  async createEngineer(input: CreateEngineerDto) { const item = await prisma.engineer.create({ data: input, include: engineerInclude }); return mapEngineer(item as EngineerRecord); }
  async listEngineers() { const items = await prisma.engineer.findMany({ include: engineerInclude, orderBy: { name: "asc" } }); return items.map((item) => mapEngineer(item as EngineerRecord)); }
  async findEngineer(id: string) { const item = await prisma.engineer.findUnique({ where: { id }, include: engineerInclude }); return item ? mapEngineer(item as EngineerRecord) : null; }
  async createTeam(input: CreateTeamDto) { const item = await prisma.team.create({ data: input, include: { members: { include: { engineer: { include: { availability: true } } } }, _count: { select: { workOrders: { where: { status: { notIn: ["Completed", "Cancelled"] } } } } } } }); return this.mapTeam(item, new Date()); }
  async listTeams(at: Date) { const items = await prisma.team.findMany({ include: { members: { include: { engineer: { include: { availability: true } } }, orderBy: { role: "asc" } }, _count: { select: { workOrders: { where: { status: { notIn: ["Completed", "Cancelled"] } } } } } }, orderBy: { name: "asc" } }); return items.map((item) => this.mapTeam(item, at)); }
  async addSkill(input: SkillInputDto) { const skill = await prisma.skill.upsert({ where: { name: input.name }, create: { name: input.name, category: input.category }, update: { category: input.category } }); await prisma.engineerSkill.upsert({ where: { engineerId_skillId: { engineerId: input.engineerId, skillId: skill.id } }, create: { engineerId: input.engineerId, skillId: skill.id, proficiency: input.proficiency, yearsExperience: input.yearsExperience }, update: { proficiency: input.proficiency, yearsExperience: input.yearsExperience } }); }
  async addCertification(input: CertificationInputDto) { await prisma.certification.create({ data: { ...input, credentialCode: input.credentialCode ?? null, issuedAt: input.issuedAt ?? null, expiresAt: input.expiresAt ?? null } }); }
  async addAvailability(input: AvailabilityInputDto) { await prisma.engineerAvailability.create({ data: { ...input, note: input.note ?? null } }); }
  async addTeamMember(input: TeamMembershipInputDto) { await prisma.teamMembership.upsert({ where: { teamId_engineerId: { teamId: input.teamId, engineerId: input.engineerId } }, create: input, update: { role: input.role } }); }
  async getAssignmentWorkOrder(id: string) { const item = await prisma.workOrder.findUnique({ where: { id }, select: { id: true, title: true, description: true, priority: true, scheduledStart: true, asset: { select: { equipment: { select: { category: true } } } } } }); return item ? { id: item.id, title: item.title, description: item.description, priority: item.priority, scheduledStart: item.scheduledStart, assetCategory: item.asset.equipment.category } : null; }
  async listAssignmentCandidates(at: Date): Promise<AssignmentCandidate[]> { const engineers = await this.listEngineers(); return engineers.map((engineer) => ({ ...engineer, unavailableAt: engineer.availability.some((slot) => slot.startsAt <= at && slot.endsAt >= at && slot.status !== "Available") })); }
  private mapTeam(item: { id: string; name: string; description: string | null; active: boolean; members: Array<{ engineerId: string; role: string; engineer: { name: string; availability: Array<{ startsAt: Date; endsAt: Date; status: string }> } }>; _count: { workOrders: number } }, at: Date): Team { return { id: item.id, name: item.name, description: item.description, active: item.active, activeWorkOrders: item._count.workOrders, members: item.members.map((member) => ({ engineerId: member.engineerId, name: member.engineer.name, role: member.role, available: !member.engineer.availability.some((slot) => slot.startsAt <= at && slot.endsAt >= at && slot.status !== "Available") })) }; }
}
