import "server-only";
import { isLowStock, type InventoryItem, type InventoryQuery, type InventoryRecommendation, type Page, type SparePart } from "@/domain/entities/Inventory";
import type { CreateInventoryItemDto, CreatePartDto, UpdatePartDto, WorkOrderPartInputDto } from "@/dto/inventory.dto";
import { prisma } from "@/lib/prisma";
import type { InventoryRepository, InventorySummary } from "@/repositories/InventoryRepository";
const page = <T>(items: T[], query: InventoryQuery, total: number): Page<T> => ({ items, page: query.page ?? 1, pageSize: query.pageSize ?? 25, total, pageCount: Math.ceil(total / (query.pageSize ?? 25)) });
const parseTypes = (value: string) => { try { const parsed = JSON.parse(value); return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === "string") : []; } catch { return []; } };
const partInclude = { supplier: { select: { id: true, name: true } }, inventoryItems: { select: { quantity: true, reserved: true, available: true } } } as const;
const mapPart = (item: { id: string; partNumber: string; barcode: string | null; qrCode: string | null; name: string; description: string | null; manufacturer: string | null; category: string; image: string | null; compatibleAssetTypes: string; unitCost: number; reorderLevel: number; minimumStock: number; maximumStock: number; leadTimeDays: number; supplier: { id: string; name: string } | null; inventoryItems: Array<{ quantity: number; available: number }> }): SparePart => { const totalQuantity = item.inventoryItems.reduce((sum, entry) => sum + entry.quantity, 0); const availableQuantity = item.inventoryItems.reduce((sum, entry) => sum + entry.available, 0); return { ...item, compatibleAssetTypes: parseTypes(item.compatibleAssetTypes), totalQuantity, availableQuantity, lowStock: isLowStock(availableQuantity, item.reorderLevel) }; };
const itemInclude = { warehouse: { select: { code: true, name: true } }, sparePart: { select: { partNumber: true, name: true, reorderLevel: true } } } as const;
const mapItem = (item: { id: string; warehouseId: string; sparePartId: string; quantity: number; reserved: number; available: number; shelf: string | null; lastMovementAt: Date | null; warehouse: { code: string; name: string }; sparePart: { partNumber: string; name: string; reorderLevel: number } }): InventoryItem => ({ id: item.id, warehouseId: item.warehouseId, warehouseCode: item.warehouse.code, warehouseName: item.warehouse.name, sparePartId: item.sparePartId, partNumber: item.sparePart.partNumber, sparePartName: item.sparePart.name, quantity: item.quantity, reserved: item.reserved, available: item.available, shelf: item.shelf, lastMovementAt: item.lastMovementAt, reorderLevel: item.sparePart.reorderLevel, lowStock: isLowStock(item.available, item.sparePart.reorderLevel) });
export class InsufficientStockError extends Error {}
export class PrismaInventoryRepository implements InventoryRepository {
  async createPart(input: CreatePartDto) { return mapPart(await prisma.sparePart.create({ data: { ...input, barcode: input.barcode ?? null, qrCode: input.qrCode ?? null, description: input.description ?? null, manufacturer: input.manufacturer ?? null, image: input.image ?? null, compatibleAssetTypes: JSON.stringify(input.compatibleAssetTypes ?? []), supplierId: input.supplierId ?? null }, include: partInclude })); }
  async updatePart(input: UpdatePartDto) { const { id, compatibleAssetTypes, ...data } = input; return mapPart(await prisma.sparePart.update({ where: { id }, data: { ...data, compatibleAssetTypes: compatibleAssetTypes === undefined ? undefined : JSON.stringify(compatibleAssetTypes) }, include: partInclude })); }
  async listParts(query: InventoryQuery) { const search = query.search; const where = { OR: search ? [{ partNumber: { contains: search } }, { name: { contains: search } }, { manufacturer: { contains: search } }, { category: { contains: search } }, { barcode: { contains: search } }] : undefined }; const all = await prisma.sparePart.findMany({ where, include: partInclude, orderBy: { name: "asc" } }); const filtered = all.map(mapPart).filter((item) => query.status === "LOW_STOCK" ? item.lowStock : query.status === "OUT_OF_STOCK" ? item.availableQuantity === 0 : query.status === "IN_STOCK" ? item.availableQuantity > 0 : true); const start = ((query.page ?? 1) - 1) * (query.pageSize ?? 25); return page(filtered.slice(start, start + (query.pageSize ?? 25)), query, filtered.length); }
  async createInventoryItem(input: CreateInventoryItemDto) { const quantity = input.quantity ?? 0; const reserved = input.reserved ?? 0; const available = quantity - reserved; const item = await prisma.inventoryItem.upsert({ where: { warehouseId_sparePartId: { warehouseId: input.warehouseId, sparePartId: input.sparePartId } }, create: { warehouseId: input.warehouseId, sparePartId: input.sparePartId, quantity, reserved, available, shelf: input.shelf ?? null }, update: { quantity, reserved, available, shelf: input.shelf ?? null }, include: itemInclude }); return mapItem(item); }
  async listInventoryItems(query: InventoryQuery) { const search = query.search; const where = { warehouseId: query.warehouseId || undefined, OR: search ? [{ sparePart: { partNumber: { contains: search } } }, { sparePart: { name: { contains: search } } }, { warehouse: { name: { contains: search } } }, { shelf: { contains: search } }] : undefined }; const all = await prisma.inventoryItem.findMany({ where, include: itemInclude, orderBy: query.sort === "quantity" ? { available: "asc" } : query.sort === "updated" ? { lastMovementAt: "desc" } : { sparePart: { name: "asc" } } }); const filtered = all.map(mapItem).filter((item) => query.status === "LOW_STOCK" ? item.lowStock : query.status === "OUT_OF_STOCK" ? item.available === 0 : query.status === "IN_STOCK" ? item.available > 0 : true); const start = ((query.page ?? 1) - 1) * (query.pageSize ?? 25); return page(filtered.slice(start, start + (query.pageSize ?? 25)), query, filtered.length); }
  async summary(): Promise<InventorySummary> { const [warehouses, parts, items] = await Promise.all([prisma.warehouse.count(), this.listParts({ pageSize: 100 }), this.listInventoryItems({ pageSize: 100 })]); return { warehouses, spareParts: parts.total, totalUnits: items.items.reduce((sum, item) => sum + item.quantity, 0), lowStockItems: items.items.filter((item) => item.lowStock).length, inventoryValue: parts.items.reduce((sum, item) => sum + item.totalQuantity * item.unitCost, 0) }; }
  async reserve(inventoryItemId: string, quantity: number) { const current = await prisma.inventoryItem.findUniqueOrThrow({ where: { id: inventoryItemId } }); if (current.available < quantity) throw new InsufficientStockError("Insufficient available stock to reserve."); return mapItem(await prisma.inventoryItem.update({ where: { id: inventoryItemId }, data: { reserved: { increment: quantity }, available: { decrement: quantity } }, include: itemInclude })); }
  async release(inventoryItemId: string, quantity: number) { const current = await prisma.inventoryItem.findUniqueOrThrow({ where: { id: inventoryItemId } }); if (current.reserved < quantity) throw new InsufficientStockError("Cannot release more stock than is reserved."); return mapItem(await prisma.inventoryItem.update({ where: { id: inventoryItemId }, data: { reserved: { decrement: quantity }, available: { increment: quantity } }, include: itemInclude })); }
  async addWorkOrderPart(input: WorkOrderPartInputDto) { await prisma.$transaction(async (tx) => { const current = await tx.inventoryItem.findUniqueOrThrow({ where: { id: input.inventoryItemId } }); const existing = await tx.workOrderPart.findUnique({ where: { workOrderId_inventoryItemId: { workOrderId: input.workOrderId, inventoryItemId: input.inventoryItemId } } }); const extra = input.quantity - (existing?.quantity ?? 0); if (extra > current.available) throw new InsufficientStockError("Insufficient available stock for this work order allocation."); if (extra < 0 && current.reserved < -extra) throw new InsufficientStockError("Cannot release more stock than is reserved."); await tx.inventoryItem.update({ where: { id: current.id }, data: { reserved: { increment: extra }, available: { decrement: extra } } }); await tx.workOrderPart.upsert({ where: { workOrderId_inventoryItemId: { workOrderId: input.workOrderId, inventoryItemId: input.inventoryItemId } }, create: input, update: { quantity: input.quantity, deductedAt: null } }); }); }
  async recommendParts(values: string[]): Promise<InventoryRecommendation[]> { const terms = values.flatMap((value) => value.toLowerCase().split(/[^a-z0-9]+/)).filter((value) => value.length > 2); const parts = await prisma.sparePart.findMany({ include: { supplier: { select: { name: true } }, inventoryItems: { include: { warehouse: { select: { name: true } } }, orderBy: { available: "desc" } } } }); return parts.filter((part) => terms.some((term) => `${part.name} ${part.category} ${part.description ?? ""}`.toLowerCase().includes(term))).map((part) => { const best = part.inventoryItems[0]; const total = part.inventoryItems.reduce((sum, item) => sum + item.available, 0); const ready = total > 0; return { sparePartId: part.id, partNumber: part.partNumber, name: part.name, availableQuantity: total, warehouseName: best?.warehouse.name ?? null, shelf: best?.shelf ?? null, suggestedOrderQuantity: Math.max(0, Math.max(part.minimumStock, part.reorderLevel) - total), supplierName: part.supplier?.name ?? null, repairReadiness: ready ? "Repair can begin immediately." : `Procurement required; estimated lead time ${part.leadTimeDays} days.`, reason: ready ? "Matching part is available in inventory." : "Matching part is unavailable or below required stock." }; }); }
}
