import "server-only";
import type { InventoryItem, InventoryRecommendation, SparePart, StockMovement, Supplier, Warehouse } from "@/domain/entities/Inventory";
import type { InventoryItemInputDto, SparePartInputDto, StockMovementInputDto, SupplierInputDto, WarehouseInputDto, WorkOrderPartInputDto } from "@/dto/inventory.dto";
import { prisma } from "@/lib/prisma";
import type { InventoryRepository } from "@/repositories/InventoryRepository";

const mapWarehouse = (item: { id: string; code: string; name: string; location: string | null; active: boolean; inventoryItems: Array<{ quantity: number }> }): Warehouse => ({ id: item.id, code: item.code, name: item.name, location: item.location, active: item.active, itemCount: item.inventoryItems.length, totalQuantity: item.inventoryItems.reduce((sum, entry) => sum + entry.quantity, 0) });
const mapSupplier = (item: { id: string; code: string; name: string; contactName: string | null; email: string | null; phone: string | null; leadTimeDays: number; active: boolean }): Supplier => item;
const mapPart = (item: { id: string; sku: string; name: string; description: string | null; category: string; unit: string; unitCost: number; reorderPoint: number; reorderQuantity: number; active: boolean; supplier: { id: string; name: string } | null; inventoryItems: Array<{ quantity: number; reserved: number }> }): SparePart => { const totalQuantity = item.inventoryItems.reduce((sum, entry) => sum + entry.quantity, 0); const availableQuantity = item.inventoryItems.reduce((sum, entry) => sum + entry.quantity - entry.reserved, 0); return { id: item.id, sku: item.sku, name: item.name, description: item.description, category: item.category, unit: item.unit, unitCost: item.unitCost, reorderPoint: item.reorderPoint, reorderQuantity: item.reorderQuantity, supplier: item.supplier, totalQuantity, availableQuantity, lowStock: availableQuantity <= item.reorderPoint }; };
const mapItem = (item: { id: string; warehouseId: string; sparePartId: string; quantity: number; reserved: number; binLocation: string | null; warehouse: { code: string; name: string }; sparePart: { sku: string; name: string; reorderPoint: number } }): InventoryItem => ({ id: item.id, warehouseId: item.warehouseId, warehouseCode: item.warehouse.code, warehouseName: item.warehouse.name, sparePartId: item.sparePartId, sku: item.sparePart.sku, sparePartName: item.sparePart.name, quantity: item.quantity, reserved: item.reserved, available: item.quantity - item.reserved, binLocation: item.binLocation, reorderPoint: item.sparePart.reorderPoint, lowStock: item.quantity - item.reserved <= item.sparePart.reorderPoint });
const mapMovement = (item: { id: string; warehouseId: string; sparePartId: string; workOrderId: string | null; type: string; quantity: number; balanceAfter: number; reason: string; reference: string | null; createdAt: Date }): StockMovement => ({ ...item, type: item.type as StockMovement["type"] });

export class InsufficientStockError extends Error {}

export class PrismaInventoryRepository implements InventoryRepository {
  async createWarehouse(input: WarehouseInputDto) { return mapWarehouse(await prisma.warehouse.create({ data: { ...input, location: input.location ?? null }, include: { inventoryItems: { select: { quantity: true } } } })); }
  async listWarehouses() { return (await prisma.warehouse.findMany({ include: { inventoryItems: { select: { quantity: true } } }, orderBy: { name: "asc" } })).map(mapWarehouse); }
  async createSupplier(input: SupplierInputDto) { return mapSupplier(await prisma.supplier.create({ data: { ...input, contactName: input.contactName ?? null, email: input.email ?? null, phone: input.phone ?? null } })); }
  async listSuppliers() { return (await prisma.supplier.findMany({ orderBy: { name: "asc" } })).map(mapSupplier); }
  async createSparePart(input: SparePartInputDto) { const item = await prisma.sparePart.create({ data: { ...input, description: input.description ?? null, supplierId: input.supplierId ?? null }, include: { supplier: { select: { id: true, name: true } }, inventoryItems: { select: { quantity: true, reserved: true } } } }); return mapPart(item); }
  async listSpareParts() { const items = await prisma.sparePart.findMany({ include: { supplier: { select: { id: true, name: true } }, inventoryItems: { select: { quantity: true, reserved: true } } }, orderBy: [{ category: "asc" }, { name: "asc" }] }); return items.map(mapPart); }
  async setInventoryItem(input: InventoryItemInputDto) { const item = await prisma.inventoryItem.upsert({ where: { warehouseId_sparePartId: { warehouseId: input.warehouseId, sparePartId: input.sparePartId } }, create: { ...input, binLocation: input.binLocation ?? null }, update: { quantity: input.quantity, reserved: input.reserved, binLocation: input.binLocation ?? null }, include: { warehouse: { select: { code: true, name: true } }, sparePart: { select: { sku: true, name: true, reorderPoint: true } } } }); return mapItem(item); }
  async listInventoryItems() { const items = await prisma.inventoryItem.findMany({ include: { warehouse: { select: { code: true, name: true } }, sparePart: { select: { sku: true, name: true, reorderPoint: true } } }, orderBy: [{ warehouse: { name: "asc" } }, { sparePart: { name: "asc" } }] }); return items.map(mapItem); }
  async summary() { const [warehouses, parts, items] = await Promise.all([prisma.warehouse.count({ where: { active: true } }), this.listSpareParts(), this.listInventoryItems()]); return { warehouses, spareParts: parts.length, totalUnits: items.reduce((sum, item) => sum + item.quantity, 0), lowStockItems: items.filter((item) => item.lowStock).length, inventoryValue: parts.reduce((sum, part) => sum + part.totalQuantity * part.unitCost, 0) }; }
  async recordMovement(input: StockMovementInputDto) { return prisma.$transaction(async (tx) => { const current = await tx.inventoryItem.findUnique({ where: { warehouseId_sparePartId: { warehouseId: input.warehouseId, sparePartId: input.sparePartId } } }); if (!current) throw new InsufficientStockError("Inventory item was not found."); const balanceAfter = current.quantity + input.quantity; if (balanceAfter < current.reserved || balanceAfter < 0) throw new InsufficientStockError("Stock movement would reduce inventory below available quantity."); await tx.inventoryItem.update({ where: { id: current.id }, data: { quantity: balanceAfter } }); return mapMovement(await tx.stockMovement.create({ data: { warehouseId: input.warehouseId, sparePartId: input.sparePartId, type: input.type, quantity: input.quantity, balanceAfter, reason: input.reason, reference: input.reference ?? null } })); }); }
  async listMovements(limit = 50) { return (await prisma.stockMovement.findMany({ orderBy: { createdAt: "desc" }, take: limit })).map(mapMovement); }
  async addWorkOrderPart(input: WorkOrderPartInputDto) { await prisma.workOrderPart.upsert({ where: { workOrderId_sparePartId_warehouseId: input }, create: input, update: { quantity: input.quantity, deductedAt: null } }); }
  async deductWorkOrderParts(workOrderId: string, completedAt: Date) { return prisma.$transaction(async (tx) => { const parts = await tx.workOrderPart.findMany({ where: { workOrderId, deductedAt: null }, include: { sparePart: { select: { sku: true } }, workOrder: { select: { assetId: true } } } }); const movements: StockMovement[] = []; for (const part of parts) { const item = await tx.inventoryItem.findUnique({ where: { warehouseId_sparePartId: { warehouseId: part.warehouseId, sparePartId: part.sparePartId } } }); if (!item || item.quantity - item.reserved < part.quantity) throw new InsufficientStockError(`Insufficient stock for ${part.sparePart.sku}.`); const balanceAfter = item.quantity - part.quantity; await tx.inventoryItem.update({ where: { id: item.id }, data: { quantity: balanceAfter } }); const movement = await tx.stockMovement.create({ data: { warehouseId: part.warehouseId, sparePartId: part.sparePartId, assetId: part.workOrder.assetId, workOrderId, type: "Issue", quantity: -part.quantity, balanceAfter, reason: "Automatic deduction for completed work order", reference: workOrderId, createdAt: completedAt } }); await tx.workOrderPart.update({ where: { id: part.id }, data: { deductedAt: completedAt } }); movements.push(mapMovement(movement)); } return movements; }); }
  async recommendParts(values: string[]): Promise<InventoryRecommendation[]> { const terms = values.flatMap((value) => value.toLowerCase().split(/[^a-z0-9]+/)).filter((value) => value.length > 2); return (await this.listSpareParts()).filter((part) => terms.some((term) => `${part.name} ${part.category} ${part.description ?? ""}`.toLowerCase().includes(term))).map((part) => ({ sparePartId: part.id, sku: part.sku, name: part.name, availableQuantity: part.availableQuantity, suggestedOrderQuantity: part.lowStock ? part.reorderQuantity : 0, supplierName: part.supplier?.name ?? null, reason: part.lowStock ? "Matches the recommendation and is at or below its reorder point." : "Matches the tools or materials referenced by the recommendation." })); }
  async inventoryContextForAssets(assetIds: string[]) { const assets = await prisma.asset.findMany({ where: { assetId: { in: [...new Set(assetIds)] } }, select: { assetId: true, workOrders: { select: { id: true, parts: { include: { sparePart: { include: { supplier: { select: { name: true } }, inventoryItems: { select: { quantity: true, reserved: true } } } } } } } } } }); return assets.map((asset) => ({ assetId: asset.assetId, lowStock: asset.workOrders.flatMap((order) => order.parts).filter((part) => part.sparePart.inventoryItems.reduce((sum, item) => sum + item.quantity - item.reserved, 0) <= part.sparePart.reorderPoint).map((part) => ({ sparePartId: part.sparePart.id, sku: part.sparePart.sku, name: part.sparePart.name, availableQuantity: part.sparePart.inventoryItems.reduce((sum, item) => sum + item.quantity - item.reserved, 0), suggestedOrderQuantity: part.sparePart.reorderQuantity, supplierName: part.sparePart.supplier?.name ?? null, reason: "Allocated part is at or below its reorder point." })), allocatedParts: asset.workOrders.flatMap((order) => order.parts.map((part) => ({ workOrderId: order.id, sku: part.sparePart.sku, name: part.sparePart.name, quantity: part.quantity, deducted: part.deductedAt !== null }))) })); }
}
