"use server";
import { revalidatePath } from "next/cache";
import { adjustInventorySchema, createInventoryItemSchema, createPartSchema, createSupplierSchema, createWarehouseSchema, stockMovementSchema, transferInventorySchema, workOrderPartInputSchema } from "@/dto/inventory.dto";
import { createInventoryService, createStockMovementService, createSupplierService, createWarehouseService } from "@/services/inventoryFactory";
const number = (value: FormDataEntryValue | null) => Number(value ?? 0);
const text = (value: FormDataEntryValue | null) => typeof value === "string" && value ? value : null;
const refresh = () => ["/dashboard/inventory", "/dashboard/spare-parts", "/dashboard/warehouses", "/dashboard/suppliers"].forEach((path) => revalidatePath(path));
export async function createWarehouse(formData: FormData) { await createWarehouseService().create(createWarehouseSchema.parse({ code: formData.get("code"), name: formData.get("name"), description: text(formData.get("description")), location: text(formData.get("location")), manager: text(formData.get("manager")) })); refresh(); }
export async function createSupplier(formData: FormData) { await createSupplierService().create(createSupplierSchema.parse({ supplierCode: formData.get("supplierCode"), name: formData.get("name"), email: text(formData.get("email")), phone: text(formData.get("phone")), website: text(formData.get("website")), address: text(formData.get("address")), leadTimeDays: number(formData.get("leadTimeDays")), preferredSupplier: formData.get("preferredSupplier") === "on", rating: number(formData.get("rating")) })); refresh(); }
export async function createSparePart(formData: FormData) { await createInventoryService().createPart(createPartSchema.parse({ partNumber: formData.get("partNumber"), barcode: text(formData.get("barcode")), qrCode: text(formData.get("qrCode")), name: formData.get("name"), description: text(formData.get("description")), manufacturer: text(formData.get("manufacturer")), category: formData.get("category"), image: text(formData.get("image")), compatibleAssetTypes: String(formData.get("compatibleAssetTypes") ?? "").split(",").map((value) => value.trim()).filter(Boolean), unitCost: number(formData.get("unitCost")), reorderLevel: number(formData.get("reorderLevel")), minimumStock: number(formData.get("minimumStock")), maximumStock: number(formData.get("maximumStock")), leadTimeDays: number(formData.get("leadTimeDays")), supplierId: text(formData.get("supplierId")) })); refresh(); }
export async function createInventoryItem(formData: FormData) { await createInventoryService().createInventoryItem(createInventoryItemSchema.parse({ warehouseId: formData.get("warehouseId"), sparePartId: formData.get("sparePartId"), quantity: number(formData.get("quantity")), reserved: number(formData.get("reserved")), shelf: text(formData.get("shelf")) })); refresh(); }
export async function recordStockMovement(formData: FormData) { await createStockMovementService().record(stockMovementSchema.parse({ inventoryItemId: formData.get("inventoryItemId"), movementType: formData.get("movementType"), quantity: number(formData.get("quantity")), performedBy: formData.get("performedBy"), reference: text(formData.get("reference")), notes: text(formData.get("notes")) })); refresh(); }
export async function adjustInventory(formData: FormData) { await createStockMovementService().adjust(adjustInventorySchema.parse({ inventoryItemId: formData.get("inventoryItemId"), adjustment: number(formData.get("adjustment")), performedBy: formData.get("performedBy"), reference: text(formData.get("reference")), notes: text(formData.get("notes")) })); refresh(); }
export async function transferInventory(formData: FormData) { await createStockMovementService().transfer(transferInventorySchema.parse({ sourceInventoryItemId: formData.get("sourceInventoryItemId"), destinationInventoryItemId: formData.get("destinationInventoryItemId"), quantity: number(formData.get("quantity")), performedBy: formData.get("performedBy"), reference: text(formData.get("reference")), notes: text(formData.get("notes")) })); refresh(); }
export async function allocateWorkOrderPart(formData: FormData) { await createInventoryService().allocateToWorkOrder(workOrderPartInputSchema.parse({ workOrderId: formData.get("workOrderId"), inventoryItemId: formData.get("inventoryItemId"), quantity: number(formData.get("quantity")) })); refresh(); }
