import { z } from "zod";

export const warehouseInputSchema = z.object({ code: z.string().trim().min(2).max(30).transform((value) => value.toUpperCase()), name: z.string().trim().min(2).max(120), location: z.string().trim().max(250).nullable().optional(), active: z.boolean().default(true) });
export const supplierInputSchema = z.object({ code: z.string().trim().min(2).max(30).transform((value) => value.toUpperCase()), name: z.string().trim().min(2).max(160), contactName: z.string().trim().max(120).nullable().optional(), email: z.email().nullable().optional(), phone: z.string().trim().max(40).nullable().optional(), leadTimeDays: z.number().int().min(0).max(365).default(0), active: z.boolean().default(true) });
export const sparePartInputSchema = z.object({ sku: z.string().trim().min(2).max(60).transform((value) => value.toUpperCase()), name: z.string().trim().min(2).max(160), description: z.string().trim().max(2000).nullable().optional(), category: z.string().trim().min(2).max(100), unit: z.string().trim().min(1).max(30).default("each"), unitCost: z.number().nonnegative().max(100_000_000).default(0), reorderPoint: z.number().int().nonnegative().max(1_000_000).default(0), reorderQuantity: z.number().int().positive().max(1_000_000).default(1), supplierId: z.string().min(1).nullable().optional(), active: z.boolean().default(true) });
export const inventoryItemInputSchema = z.object({ warehouseId: z.string().min(1), sparePartId: z.string().min(1), quantity: z.number().int().nonnegative().max(1_000_000_000).default(0), reserved: z.number().int().nonnegative().max(1_000_000_000).default(0), binLocation: z.string().trim().max(80).nullable().optional() }).refine((value) => value.reserved <= value.quantity, { message: "Reserved stock cannot exceed quantity.", path: ["reserved"] });
export const stockMovementInputSchema = z.object({ warehouseId: z.string().min(1), sparePartId: z.string().min(1), type: z.enum(["Receipt", "Issue", "Adjustment", "Return"]), quantity: z.number().int().refine((value) => value !== 0, "Movement quantity cannot be zero."), reason: z.string().trim().min(2).max(500), reference: z.string().trim().max(120).nullable().optional() }).superRefine((value, context) => { if (["Receipt", "Return"].includes(value.type) && value.quantity < 0) context.addIssue({ code: "custom", message: `${value.type} quantity must be positive.`, path: ["quantity"] }); if (value.type === "Issue" && value.quantity > 0) context.addIssue({ code: "custom", message: "Issue quantity must be negative.", path: ["quantity"] }); });
export const workOrderPartInputSchema = z.object({ workOrderId: z.string().min(1), sparePartId: z.string().min(1), warehouseId: z.string().min(1), quantity: z.number().int().positive().max(1_000_000) });
export type WarehouseInputDto = z.input<typeof warehouseInputSchema>;
export type SupplierInputDto = z.input<typeof supplierInputSchema>;
export type SparePartInputDto = z.input<typeof sparePartInputSchema>;
export type InventoryItemInputDto = z.input<typeof inventoryItemInputSchema>;
export type StockMovementInputDto = z.input<typeof stockMovementInputSchema>;
export type WorkOrderPartInputDto = z.input<typeof workOrderPartInputSchema>;
