import Link from "next/link";
import { SyncStatusPanel } from "@/components/mobile/SyncStatusPanel";
import { createMobileFieldService } from "@/services/mobile/mobileFactory";
import { createSyncRepository } from "@/services/mobile/syncFactory";

export const dynamic = "force-dynamic";
export default async function MobileDashboardPage() {
  const syncRepository = createSyncRepository();
  const [orders, syncSummary, syncItems] = await Promise.all([createMobileFieldService().dashboard(), syncRepository.summary(), syncRepository.list()]);
  const urgent = orders.filter((order) => order.priority === "Critical" || order.priority === "High");
  return <div className="space-y-5"><section className="rounded-3xl bg-gradient-to-br from-cyan-600 to-blue-700 p-6 text-white"><p className="text-xs uppercase tracking-[0.2em] text-cyan-100">Field Engineer Mobile</p><h1 className="mt-2 text-2xl font-semibold">Today’s engineering work</h1><p className="mt-2 text-sm text-cyan-50">Capture field evidence, location, voice notes, and signatures from a mobile-first workspace.</p></section><SyncStatusPanel summary={syncSummary} failed={syncItems.filter((item) => item.status === "Failed")}/><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><p className="text-xs text-slate-500">Active</p><p className="mt-1 text-3xl font-semibold">{orders.length}</p></div><div className="rounded-2xl border border-red-200 bg-red-50 p-4 dark:border-red-900 dark:bg-red-950/30"><p className="text-xs text-red-600">High priority</p><p className="mt-1 text-3xl font-semibold">{urgent.length}</p></div></div><div className="grid grid-cols-2 gap-3"><Link href="/mobile/work-orders" className="rounded-2xl bg-cyan-600 p-4 text-center text-sm font-semibold text-white">Open work orders</Link><Link href="/mobile/scan" className="rounded-2xl border border-slate-300 p-4 text-center text-sm font-semibold dark:border-slate-700">Scan QR / barcode</Link></div><section><h2 className="font-semibold">Next work orders</h2><div className="mt-3 space-y-3">{orders.slice(0, 5).map((order) => <Link key={order.id} href={`/mobile/work-orders/${order.id}`} className="block rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><div className="flex justify-between gap-3"><p className="font-semibold">{order.title}</p><span className="text-xs font-medium">{order.priority}</span></div><p className="mt-1 text-xs text-slate-500">{order.assetId} · {order.status}</p></Link>)}</div></section></div>;
}
