export const stockMovementTypes = ["RECEIVED", "ISSUED", "RETURNED", "TRANSFERRED", "ADJUSTED", "CONSUMED"] as const;
export type StockMovementType = typeof stockMovementTypes[number];
export interface Page<T> { items: T[]; page: number; pageSize: number; total: number; pageCount: number }
export interface InventoryQuery { search?: string; warehouseId?: string; status?: "ALL" | "LOW_STOCK" | "OUT_OF_STOCK" | "IN_STOCK"; sort?: "name" | "quantity" | "updated"; page?: number; pageSize?: number }
export interface Warehouse { id: string; code: string; name: string; description: string | null; location: string | null; manager: string | null; createdAt: Date; updatedAt: Date; itemCount: number; totalQuantity: number }
export interface Supplier { id: string; supplierCode: string; name: string; email: string | null; phone: string | null; website: string | null; address: string | null; leadTimeDays: number; preferredSupplier: boolean; rating: number; createdAt: Date }
export interface SparePart { id: string; partNumber: string; barcode: string | null; qrCode: string | null; name: string; description: string | null; manufacturer: string | null; category: string; image: string | null; compatibleAssetTypes: string[]; unitCost: number; reorderLevel: number; minimumStock: number; maximumStock: number; leadTimeDays: number; supplier: { id: string; name: string } | null; totalQuantity: number; availableQuantity: number; lowStock: boolean }
export interface InventoryItem { id: string; warehouseId: string; warehouseCode: string; warehouseName: string; sparePartId: string; partNumber: string; sparePartName: string; quantity: number; reserved: number; available: number; shelf: string | null; lastMovementAt: Date | null; reorderLevel: number; lowStock: boolean }
export interface StockMovement { id: string; inventoryItemId: string; destinationInventoryItemId: string | null; workOrderId: string | null; movementType: StockMovementType; quantity: number; balanceAfter: number; performedBy: string; reference: string | null; notes: string | null; createdAt: Date }
export interface InventoryRecommendation { sparePartId: string; partNumber: string; name: string; availableQuantity: number; warehouseName: string | null; shelf: string | null; suggestedOrderQuantity: number; supplierName: string | null; repairReadiness: string; reason: string }
export const isLowStock = (available: number, reorderLevel: number) => available <= reorderLevel;
