import Link from "next/link";
import type { AssetTimelineDto } from "@/dto/timeline.dto";

const tone = { Inspection: "bg-violet-500", "Sensor Reading": "bg-cyan-500", Health: "bg-emerald-500", Alert: "bg-red-500", Recommendation: "bg-amber-500", Maintenance: "bg-blue-500", "Work Order": "bg-indigo-500" } as const;

export function AssetTimeline({ timeline }: { timeline: AssetTimelineDto }) {
  return <div className="space-y-6">
    <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-600">Trend explanation</p><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{timeline.trendExplanation}</p></div><div className="rounded-2xl border border-cyan-200 bg-cyan-50 p-5 dark:border-cyan-900 dark:bg-cyan-950/30"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-700 dark:text-cyan-300">AI summary</p><p className="mt-3 text-sm leading-7 text-slate-700 dark:text-slate-200">{timeline.aiSummary}</p></div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Asset timeline</h2><p className="mt-1 text-sm text-slate-500">{timeline.events.length} engineering events across the asset lifecycle.</p></div><div className="flex flex-wrap gap-2">{Object.entries(tone).map(([type, color]) => <span key={type} className="flex items-center gap-2 text-xs text-slate-500"><span className={`h-2.5 w-2.5 rounded-full ${color}`} />{type}</span>)}</div></div>
      {timeline.events.length ? <div>{timeline.events.map((event, index) => <article key={event.id} className="relative flex gap-4 pb-7 last:pb-0"><div className="relative z-10 mt-1"><span className={`block h-3.5 w-3.5 rounded-full ring-4 ring-white dark:ring-slate-900 ${tone[event.type]}`} /></div>{index < timeline.events.length - 1 ? <span className="absolute left-[6px] top-4 h-full w-px bg-slate-200 dark:bg-slate-700" /> : null}<div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-medium text-slate-500">{event.type}</span>{event.severity ? <span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs font-medium dark:bg-slate-800">{event.severity}</span> : null}</div><h3 className="mt-1 font-semibold">{event.title}</h3></div><time className="text-xs text-slate-500">{event.occurredAt.toLocaleString("en-GB")}</time></div><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{event.summary}</p>{event.type === "Alert" && typeof event.metadata.alertId === "string" ? <Link href={`/dashboard/alerts/${event.metadata.alertId}`} className="mt-2 inline-block text-xs font-medium text-cyan-600">View alert</Link> : null}{event.type === "Work Order" && typeof event.metadata.workOrderId === "string" ? <Link href={`/dashboard/work-orders/${event.metadata.workOrderId}`} className="mt-2 inline-block text-xs font-medium text-cyan-600">View work order</Link> : null}</div></article>)}</div> : <p className="text-sm text-slate-500">No engineering events have been recorded for this asset.</p>}
    </section>
  </div>;
}
