import Link from "next/link";
import { notFound } from "next/navigation";
import { acknowledgeAlert, resolveAlert } from "@/app/dashboard/alerts/actions";
import { AlertTimeline } from "@/components/alerts/AlertTimeline";
import { PageHeader } from "@/components/PageHeader";
import { createAlertService } from "@/services/alertFactory";

export const dynamic = "force-dynamic";
export default async function AlertDetailPage({ params }: { params: Promise<{ alertId: string }> }) {
  const { alertId } = await params;
  const service = createAlertService();
  const alert = await service.get(alertId); if (!alert) notFound();
  const history = await service.history(alert.id);
  return <div className="space-y-6"><div><Link href="/dashboard/alerts" className="text-sm font-medium text-cyan-600 hover:text-cyan-500">← Alert Center</Link></div><PageHeader title={alert.title} description={`${alert.assetId} · ${alert.assetName}`} /><div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]"><main className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold dark:bg-slate-800">{alert.severity}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-xs dark:bg-slate-800">{alert.status}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-xs dark:bg-slate-800">{alert.category}</span></div><dl className="mt-6 grid gap-4 sm:grid-cols-2"><div><dt className="text-xs uppercase tracking-[0.16em] text-slate-500">Source</dt><dd className="mt-1 text-sm font-medium">{alert.source}</dd></div><div><dt className="text-xs uppercase tracking-[0.16em] text-slate-500">Trigger</dt><dd className="mt-1 text-sm font-medium">{alert.triggerType ?? "System"}{alert.triggerId ? ` · ${alert.triggerId}` : ""}</dd></div><div><dt className="text-xs uppercase tracking-[0.16em] text-slate-500">Observed</dt><dd className="mt-1 text-sm font-medium">{alert.observedValue ?? "—"}</dd></div><div><dt className="text-xs uppercase tracking-[0.16em] text-slate-500">Threshold</dt><dd className="mt-1 text-sm font-medium">{alert.thresholdValue ?? "—"}</dd></div><div><dt className="text-xs uppercase tracking-[0.16em] text-slate-500">Created</dt><dd className="mt-1 text-sm font-medium">{alert.createdAt.toLocaleString("en-GB")}</dd></div><div><dt className="text-xs uppercase tracking-[0.16em] text-slate-500">Updated</dt><dd className="mt-1 text-sm font-medium">{alert.updatedAt.toLocaleString("en-GB")}</dd></div></dl></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="font-semibold">AI explanation</h2><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{alert.description}</p><h2 className="mt-6 font-semibold">Recommended action</h2><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{alert.recommendation}</p><div className="mt-6 flex gap-2">{alert.status === "Open" ? <form action={acknowledgeAlert}><input type="hidden" name="alertId" value={alert.id} /><button className="rounded-full border border-slate-300 px-4 py-2 text-sm font-medium dark:border-slate-700">Acknowledge</button></form> : null}{alert.status !== "Resolved" ? <form action={resolveAlert}><input type="hidden" name="alertId" value={alert.id} /><button className="rounded-full bg-cyan-500 px-4 py-2 text-sm font-medium text-white">Resolve</button></form> : null}</div></section></main><AlertTimeline alert={alert} history={history} /></div></div>;
}
