import Link from "next/link";
import { Button } from "@/components/Button";
import { PageHeader } from "@/components/PageHeader";
import { workOrderListQuerySchema } from "@/dto/work-order.dto";
import { createWorkOrderScheduler, createWorkOrderService } from "@/services/workOrderFactory";

export const dynamic = "force-dynamic";
const text = (value: string | string[] | undefined) => typeof value === "string" ? value : undefined;
export default async function WorkOrdersPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await createWorkOrderScheduler().run();
  const params = await searchParams; const query = workOrderListQuerySchema.parse({ status: text(params.status) || undefined, priority: text(params.priority) || undefined, assetId: text(params.assetId) || undefined, assignedTo: text(params.assignedTo) || undefined });
  const service = createWorkOrderService(); const [orders, assets] = await Promise.all([service.list(query), service.listAssetOptions()]);
  return <div className="space-y-6"><PageHeader title="Work Orders" description="Plan, assign, schedule, and track engineering work against operational assets." actions={<Button href="/dashboard/work-orders/new">Create work order</Button>} />
    <form className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 sm:grid-cols-2 xl:grid-cols-5 dark:border-slate-800 dark:bg-slate-900"><select name="status" defaultValue={query.status ?? ""} className="rounded-xl border border-slate-300 bg-transparent px-3 py-2 text-sm dark:border-slate-700"><option value="">All statuses</option>{["Draft","Scheduled","In Progress","On Hold","Completed","Cancelled"].map((value) => <option key={value}>{value}</option>)}</select><select name="priority" defaultValue={query.priority ?? ""} className="rounded-xl border border-slate-300 bg-transparent px-3 py-2 text-sm dark:border-slate-700"><option value="">All priorities</option>{["Critical","High","Medium","Low"].map((value) => <option key={value}>{value}</option>)}</select><select name="assetId" defaultValue={query.assetId ?? ""} className="rounded-xl border border-slate-300 bg-transparent px-3 py-2 text-sm dark:border-slate-700"><option value="">All assets</option>{assets.map((asset) => <option key={asset.assetId} value={asset.assetId}>{asset.assetId} · {asset.name}</option>)}</select><input name="assignedTo" defaultValue={query.assignedTo ?? ""} placeholder="Assigned engineer" className="rounded-xl border border-slate-300 bg-transparent px-3 py-2 text-sm dark:border-slate-700"/><button className="rounded-xl bg-cyan-500 px-4 py-2 text-sm font-medium text-white">Apply</button></form>
    <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900">{orders.length ? <div className="divide-y divide-slate-200 dark:divide-slate-800">{orders.map((order) => <Link key={order.id} href={`/dashboard/work-orders/${order.id}`} className="grid gap-3 p-5 hover:bg-slate-50 sm:grid-cols-[minmax(0,1fr)_140px_140px] dark:hover:bg-slate-800/50"><div><p className="font-semibold">{order.title}</p><p className="mt-1 text-sm text-slate-500">{order.assetId} · {order.assetName}{order.assignedTo ? ` · ${order.assignedTo}` : " · Unassigned"}</p></div><span className="self-center text-sm font-medium">{order.priority}</span><span className="self-center text-sm text-slate-600 dark:text-slate-300">{order.status}</span></Link>)}</div> : <p className="p-8 text-sm text-slate-500">No work orders match the selected filters.</p>}</div></div>;
}
