"use client";

import { useRef, useState } from "react";
import { queueVoiceNoteSync, saveMobileLocation, saveMobileSignature, uploadMobilePhoto } from "@/app/mobile/actions";
import { BrowserGpsCapture, BrowserVoiceNoteRecorder } from "@/infrastructure/mobile/BrowserCaptureAdapters";

export function FieldCapturePanel({ workOrderId }: { workOrderId: string }) {
  const canvas = useRef<HTMLCanvasElement>(null); const recorder = useRef(new BrowserVoiceNoteRecorder()); const [drawing, setDrawing] = useState(false); const [signature, setSignature] = useState(""); const [location, setLocation] = useState<{ latitude: number; longitude: number; accuracy: number | null } | null>(null); const [voice, setVoice] = useState<{ durationMs: number; localUri: string } | null>(null); const [recording, setRecording] = useState(false); const [message, setMessage] = useState("");
  const point = (event: React.PointerEvent<HTMLCanvasElement>) => { const target = event.currentTarget; const box = target.getBoundingClientRect(); return { x: (event.clientX - box.left) * target.width / box.width, y: (event.clientY - box.top) * target.height / box.height }; };
  const start = (event: React.PointerEvent<HTMLCanvasElement>) => { const ctx = canvas.current?.getContext("2d"); if (!ctx) return; const p = point(event); ctx.beginPath(); ctx.moveTo(p.x, p.y); ctx.lineWidth = 3; ctx.lineCap = "round"; ctx.strokeStyle = "#0891b2"; setDrawing(true); event.currentTarget.setPointerCapture(event.pointerId); };
  const move = (event: React.PointerEvent<HTMLCanvasElement>) => { if (!drawing) return; const ctx = canvas.current?.getContext("2d"); if (!ctx) return; const p = point(event); ctx.lineTo(p.x, p.y); ctx.stroke(); };
  const finish = () => { setDrawing(false); if (canvas.current) setSignature(canvas.current.toDataURL("image/png")); };
  const clear = () => { const target = canvas.current; target?.getContext("2d")?.clearRect(0, 0, target.width, target.height); setSignature(""); };
  const locate = async () => { try { const value = await new BrowserGpsCapture().capture(); setLocation(value); setMessage("GPS position ready to save."); } catch { setMessage("Location permission or GPS capture was unavailable."); } };
  const toggleVoice = async () => { try { if (!recording) { await recorder.current.start(); setRecording(true); setMessage("Recording voice note…"); } else { const note = await recorder.current.stop(workOrderId); setVoice(note); setRecording(false); const form = new FormData(); form.set("workOrderId", note.workOrderId); form.set("mimeType", note.mimeType); form.set("durationMs", String(note.durationMs)); form.set("size", String(note.size)); form.set("localUri", note.localUri); await queueVoiceNoteSync(form); setMessage("Voice note added to the persistent synchronization queue."); } } catch { setRecording(false); setMessage("Microphone capture was unavailable."); } };
  return <div className="space-y-5">
    <section className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-semibold">Camera evidence</h2><form action={uploadMobilePhoto} className="mt-3 space-y-3"><input type="hidden" name="workOrderId" value={workOrderId}/><input type="file" name="photo" accept="image/jpeg,image/png,image/webp" capture="environment" required className="block w-full text-sm"/><input name="note" placeholder="Photo note" className="w-full rounded-xl border border-slate-300 bg-transparent px-3 py-2 text-sm dark:border-slate-700"/><button className="w-full rounded-xl bg-cyan-600 px-4 py-3 text-sm font-semibold text-white">Upload photo</button></form></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-semibold">Voice note</h2><p className="mt-1 text-xs text-slate-500">Recorded locally; server synchronization is reserved for the next offline phase.</p><button type="button" onClick={toggleVoice} className="mt-3 w-full rounded-xl border border-slate-300 px-4 py-3 text-sm font-semibold dark:border-slate-700">{recording ? "Stop recording" : "Record voice note"}</button>{voice ? <audio controls src={voice.localUri} className="mt-3 w-full"/> : null}</section>
    <section className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-semibold">GPS capture</h2><button type="button" onClick={locate} className="mt-3 w-full rounded-xl border border-slate-300 px-4 py-3 text-sm font-semibold dark:border-slate-700">Capture current location</button>{location ? <form action={saveMobileLocation} className="mt-3"><input type="hidden" name="workOrderId" value={workOrderId}/><input type="hidden" name="latitude" value={location.latitude}/><input type="hidden" name="longitude" value={location.longitude}/><input type="hidden" name="accuracy" value={location.accuracy ?? ""}/><p className="mb-3 text-xs text-slate-500">{location.latitude.toFixed(5)}, {location.longitude.toFixed(5)}</p><button className="w-full rounded-xl bg-cyan-600 px-4 py-3 text-sm font-semibold text-white">Save location</button></form> : null}</section>
    <section className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-semibold">Digital signature</h2><canvas ref={canvas} width={700} height={240} onPointerDown={start} onPointerMove={move} onPointerUp={finish} onPointerCancel={finish} className="mt-3 h-36 w-full touch-none rounded-xl border border-slate-300 bg-white dark:border-slate-700" aria-label="Signature pad"/><button type="button" onClick={clear} className="mt-2 text-xs font-medium text-slate-500">Clear signature</button><form action={saveMobileSignature} className="mt-3 space-y-3"><input type="hidden" name="workOrderId" value={workOrderId}/><input type="hidden" name="signatureData" value={signature}/>{location ? <><input type="hidden" name="latitude" value={location.latitude}/><input type="hidden" name="longitude" value={location.longitude}/></> : null}<input name="signerName" required minLength={2} placeholder="Signer name" className="w-full rounded-xl border border-slate-300 bg-transparent px-3 py-2 text-sm dark:border-slate-700"/><button disabled={!signature} className="w-full rounded-xl bg-cyan-600 px-4 py-3 text-sm font-semibold text-white disabled:opacity-40">Save signature</button></form></section>
    {message ? <p role="status" className="rounded-xl bg-slate-100 p-3 text-xs text-slate-600 dark:bg-slate-800 dark:text-slate-300">{message}</p> : null}
  </div>;
}
